source.. = src/,\
           test/
output.. = bin/
source.resources/ = resources/
output.resources/ = resources/
source.template/ = template/
output.template/ = template/
source.icons/ = icons/
output.icons/ = icons/
source.images/ = images/
output.images/ = images/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               images/,\
               plugin_ja.properties,\
               plugin.properties,\
               lib/,\
               schema/,\
               lib/poi-3.7-20101029.jar,\
               resources/,\
               template/

